image: node:latest

# before_script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl

stages:
    - installs
    - staging

installs:
    stage: staging
    image: ruby:latest
  
installs:
    stage: staging
    # type: deploy
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    only:
        - chat-completion

staging:
    stage: staging
    # type: deploy
    # image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - chat-completion

