# image: node:latest

# before_script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl

# stages:
#     - staging

# staging:
#     stage: staging
#     # type: deploy
#     image: ruby:latest
#     script:
#         - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
#     only:
#         - chat-completion
