const CATEGORY = {
  BITCOIN: "BITCOIN",
  ARTICLE_REVIEW: "ARTICLE_REVIEW",
  ALTCOINS: "ALTCOINS",
  NFT: "NFT",
  ECONOMY: "ECONOMY",
  FED: "FED",
  REGULATIONS: "REGULATIONS",
  LEGISLATION: "LEGISLATION",
  TECH: "TECH",
  SERVICE_REVIEW: "SERVICE_REVIEW",
  AFFILIATE: "AFFILIATE",
  INFLATION: "INFLATION",
  GENERAL: "GENERAL",
  PROGRAMMING: "PROGRAMMING",
  // BITCOIN_MAGAZINE: "BITCOIN_MAGAZINE",
  // COINDESK: "COINDESK",
  // COINJOURNAL: "COINJOURNAL",
}

module.exports = CATEGORY