const MARKET_CATEGORIES = [
  {
    id: "business-and-industrial",
    name: "Business and Industrial",
    sub: [
      "Other Business and Industrial",
      "Industrial Kitchen Supplies",
      "Storage Containers",
      "Industrial Shelving and Racking",
    ],
  },
  {
    id: "vehicles",
    name: "Vehicles",
    sub: [
      "Vehicle Parts, Tires, and Accessories",
      "Cars and Trucks",
      "RVS, Campers and Trailers",
      "Motorcycles",
      "Boats and Watercraft",
      "ATVs and Snowmobiles",
      "Heavy Equipment",
      "Other",
      "Classic Cars",
      "Automotive Services",
    ],
  },
  {
    id: "home-appliances",
    name: "Home Appliances",
    sub: [
      "Refrigerators",
      "Appliances Miscellaneous",
      "Stoves, Ovens and Ranges",
      "Coffee Makers",
      "Microwaves and Cookers",
      "Vacuums",
      "Washers and Dryers",
      "Heaters, Humidifiers and Dehumidifiers",
      "Processors, Blenders and Juicers",
      "Dishwashers",
      "Toasters and Toaster Ovens",
      "Freezers",
      "Irons and Garment Steamers",
    ],
  },
  {
    id: "home-indoor",
    name: "Home Indoor",
    sub: [
      "Indoor Miscellaneous",
      "Sales",
      "Decoration, Arts and Collectibles",
      "Bedding",
      "Indoor Lighting and Fans",
      "Kitchen and Dining Wares",
      "Rugs, Carpets and Runners",
      "Window Treatments",
      "Storage and Organization",
      "Bathwares",
      "Holiday, Event and Seasonal",
      "Fireplace and Firewood",
    ],
  },
  {
    id: "renovation-improvement-materials-supplies",
    name: "Renovation, Improvement Materials and Supplies",
    sub: [
      "Hardware, Nails and Screws",
      "Plumbing, Sinks, Toilets and Showers",
      "Painting and Paint Supplies",
      "Heating, Cooling and Air",
      "Floors and Walls",
      "Renovation, Improvement Materials and Supplies Miscellaneous",
      "Windows, Doors and Trim",
      "Cabinets and Countertops",
      "Electrical",
      "Roofing",
    ],
  },
  {
    id: "outdoor-and-garden",
    name: "Outdoor and Garden",
    sub: [
      "Patio and Garden Furniture",
      "Plants, Fertilizer and Soil",
      "BBQs and Outdoor Cooking",
      "Hot Tubs and Pools",
      "Outdoor Décor",
      "Outdoor Miscellaneous",
      "Outdoor Tools and Storage",
      "Lawnmowers and Leaf Blowers",
      "Outdoor Lighting",
      "Decks and Fences",
      "Snowblowers",
      "Garage Doors and Openers",
    ],
  },
  {
    id: "furniture",
    name: "Furniture",
    sub: [
      "Couches and Futons",
      "Desks",
      "Chairs and Recliners",
      "Beds and Mattresses",
      "Dressers and Wardrobes",
      "Dining Tables and Sets",
      "Furniture Miscellaneous",
      "Other Tables",
      "Coffee Tables",
      "TV Tables and Entertainment Units",
      "Bookcases and Shelving Units",
      "Hutches and Display Cabinets",
      "Multi-item",
    ],
  },
  {
    id: "clothing-and-apparel",
    name: "Clothing and Apparel",
    sub: [
      "Women's - Tops and Outerwear",
      "Kids and Youth",
      "Men's",
      "Women's - Shoes",
      "Men's Shoes",
      "Women's - Dresses and Skirts",
      "Women's - Bags and Wallets",
      "Clothing and Apparel Miscellaneous",
      "Women's - Bottoms",
      "Women's - Other",
      "Multi-item",
      "Costumes",
      "Wedding",
      "Women's - Maternity",
    ],
  },
  {
    id: "sporting-goods-exercise",
    name: "Sporting Goods and Exercise",
    sub: [
      "Exercise Equipment",
      "Fishing, Camping and Outdoors",
      "Sporting Goods, Exercise and Apparel Miscellaneous",
      "Tennis and Racquet",
      "Golf",
      "Water Sports",
      "Hockey",
      "Skates and Blades",
      "Skateboard",
      "Ski",
      "Paintball",
      "Snowboard",
      "Soccer",
      "Baseball and Softball",
      "Basketball",
      "Football",
      "Lacrosse",
      "Curling",
    ],
  },
  {
    id: "computers",
    name: "Computers",
    sub: [
      "Printers, Scanners and Fax",
      "Computers Miscellaneous",
      "Laptop Accessories",
      "Cables and Connectors",
      "Networking",
      "System Components",
      "Mice, Keyboards and Webcams",
      "Monitors",
      "iPad and Tablet Accessories",
      "Services (Training and Repair)",
      "Speakers, Headsets and Mics",
      "Flash Memory and USB Sticks",
      "Software",
      "Servers",
      "Laptops",
      "Desktop Computers",
      "iPads and Tablets",
    ],
  },
  {
    id: "phones",
    name: "Phones",
    sub: [
      "Cell Phones",
      "Cell Phone Accessories",
      "Cell Phone Services",
      "Home Phones and Answering Machines",
      "Phones Miscellaneous",
    ],
  },
  {
    id: "electronics",
    name: "Electronics",
    sub: [
      "Cameras and Camcorders",
      "CDs, DVDs and Blu-ray",
      "TVs and Video",
      "Audios",
    ],
  },
  {
    id: "tools",
    name: "Tools",
    sub: [
      "Power Tools",
      "Tools Miscellaneous",
      "Hand Tools",
      "Ladders and Scaffolding",
      "Tool Storage and Benches",
      "Hardware Tools",
    ],
  },
  {
    id: "baby-items",
    name: "Baby Items",
    sub: [
      "Strollers, Carriers and Car Seats",
      "Other",
      "Feeding and High Chairs",
      "Toys",
      "Cribs",
      "Clothing - 12-18 Months",
      "Playpens, Swings and Saucers",
      "Clothing - 6-9 Months",
      "Clothing-0-3 Months",
      "Clothing-3-6 Months",
      "Multi-item",
      "Bathing and Changing",
      "Clothing-18-24 Months",
      "Clothing - 9-12 Months",
      "Clothing - 4T",
      "Gates, Monitors and Safety",
      "Clothing - 3T",
      "Clothing - 2T",
      "Clothing - 5T",
      "Clothing - Preemie",
    ],
  },
  {
    id: "bikes",
    name: "Bikes",
    sub: [
      "Road",
      "Mountain",
      "eBike",
      "Kids",
      "Clothing, Shoes and Accessories",
      "Bikes Miscellaneous",
      "Cruiser, Commuter and Hybrid",
      "Frames and Parts",
      "BMX",
      "Fixie (Single Speed)",
    ],
  },
  {
    id: "musical-instruments",
    name: "Musical Instruments",
    sub: [
      "Guitars",
      "Amps and Pedals",
      "Drums and Percussion",
      "Pianos and Keyboards",
      "Pro Audio and Recording Equipment",
      "String",
      "Musical Instruments Miscellaneous",
      "Performance and DJ Equipment",
      "Woodwind",
      "Brass",
    ],
  },
  {
    id: "video-games-consoles",
    name: "Video Games and Consoles",
    sub: [
      "Older Generation",
      "Sony Playstation 4",
      "Nintendo Wii",
      "XBOX One",
      "PC Games",
      "Sony Playstation 3",
      "XBOX 360",
      "Nintendo DS",
      "Nintendo Switch",
      "Video Games and Consoles Miscellaneous",
      "Sony Playstation 5",
      "Xbox Series X and S",
      "Nintendo Wii U",
      "Sony PSP and Vita",
    ],
  },
  {
    id: "pets",
    name: "Pets",
    sub: [
      "Supplies",
      "Accessories",
      "Cats and Kittens for Rehoming",
      "Dogs and Puppies for Rehoming",
      "Livestock",
      "Fish for Rehoming",
      "Birds for Rehoming",
      "Animal and Pet Services",
      "Small Animals for Rehoming",
      "Equestrian and Livestock Accessories",
      "Reptiles and Amphibians for Rehoming",
      "Horses and Ponies for Rehoming",
      "Lost and Found",
      "Pets Miscellaneous",
      "Other Pets for Rehoming",
      "Registered Shelter / Rescue",
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    sub: ["For Sale", "For Rent", "Real Estate Services"],
  },
  {
    id: "services",
    name: "Services",
    sub: [
      "Skilled Trades",
      "Other",
      "Cleaners and Cleaning",
      "Health and Beauty",
      "Tutors and Languages",
      "Childcare and Nanny",
      "Entertainment",
      "Wedding",
      "Music Lessons",
      "Photography and Video",
      "Travel and Vacations",
      "Fitness and Personal Trainer",
      "Moving and Storage",
      "Food and Catering",
      "Financial and Legal",
      "Digital Marketing and Digital Ads",
      "Web Development",
      "SEO",
      "Video Editing",
      "AI",
      "Web Design",
      "Automation",
    ],
  },
  {
    id: "employment",
    name: "Employment",
    sub: [
      "Skilled Trades",
      "Other",
      "Cleaners and Cleaning",
      "Health and Beauty",
      "Tutors and Languages",
      "Childcare and Nanny",
      "Entertainment",
      "Wedding",
      "Music Lessons",
      "Photography and Video",
      "Travel and Vacations",
      "Fitness and Personal Trainer",
      "Moving and Storage",
      "Food and Catering",
      "Financial and Legal",
      "IT",
      "Developer",
      "Digital Marketing",
      "Marketing",
    ],
  },
  {
    id: "community",
    name: "Community",
    sub: [
      "Other",
      "Rideshare",
      "Classes and Lessons",
      "Activities and Groups",
      "Artists and Musicians",
      "Events",
      "Lost and Found",
      "Friendship and Networking",
      "Sports Teams",
      "Long Lost Relationships Missed Connections Volunteers",
    ],
  },
  {
    id: "property-rentals",
    name: "Property Rentals",
    sub: ["Canada", "USA", "Mexico", "Other Countries", "Caribbean"],
  },
  {
    id: "jewellery-watches",
    name: "Jewellery and Watches",
    sub: [],
  },
  {
    id: "family-items",
    name: "Family Items",
    sub: [],
  },
  {
    id: "office-supplies",
    name: "Office Supplies",
    sub: [],
  },
  {
    id: "health-special-needs",
    name: "Health and Special Needs",
    sub: [],
  },
  {
    id: "tickets",
    name: "Tickets",
    sub: [],
  },
  {
    id: "crafts",
    name: "Crafts",
    sub: [],
  },
  {
    id: "other",
    name: "Other",
    sub: [],
  },
  {
    id: "free",
    name: "Free",
    sub: [],
  },
  {
    id: "books",
    name: "Books",
    sub: [],
  },
  {
    id: "toys-tangible-games",
    name: "Toys and Tangible Games",
    sub: [],
  },
];

module.exports = MARKET_CATEGORIES;
