const ROLE = {
  MASTER: "MASTER",
  USER: {
    SUBSCRIBER: {
      BASIC: "BASIC"
    },
    NOTSUBSCRIBER: "NOTSUBSCRIBER"
  }
  // MAINTAINER: "MAINTAINER",
  // DEVELOPER: "DEVELOPER"
  // EDITOR: "EDITOR",
  // EMPLOYEE: "EMPLOYEE",
  // ADVERTIZER: "ADVERTIZER",
  // CONTRACTOR: "CONTRACTOR",
  // FREELANCER: "FREELANCER",
  // INVESTOR: "INVESTOR",
}

module.exports = ROLE