const CATEGORY = require('./Types/ArticleCategories')

THIRD_PARTY_CATEGORIES = [CATEGORY.BITCOIN_MAGAZINE, CATEGORY.COINDESK, CATEGORY.COINJOURNAL]

EXTERNAL_READS_CATEGORIES = [CATEGORY.BITCOIN_MAGAZINE, CATEGORY.COINDESK, CATEGORY.COINJOURNAL]

module.exports = {THIRD_PARTY_CATEGORIES, EXTERNAL_READS_CATEGORIES}