// const CATEGORY = require('./Types/ArticleCategories')
const SOURCES = require('./Types/ArticleSources')

THIRD_PARTY_SOURCES = [SOURCES.BITCOIN_MAGAZINE, SOURCES.COINDESK, SOURCES.COINJOURNAL]

EXTERNAL_READS_SOURCES = THIRD_PARTY_SOURCES

module.exports = {THIRD_PARTY_SOURCES, EXTERNAL_READS_SOURCES}