const CATEGORY = require('./Types/ArticleCategories')

THIRD_PARTY_CATEGORIES = [CATEGORY.BITCOIN_MAGAZINE, CATEGORY.COINDESK]

EXTERNAL_READS_CATEGORIES = [CATEGORY.BITCOIN_MAGAZINE, CATEGORY.COINDESK]

module.exports = {THIRD_PARTY_CATEGORIES, EXTERNAL_READS_CATEGORIES}