const ROLE = {
  MASTER: "MASTER",
  MAINTAINER: "MAINTAINER",
  EDITOR: "EDITOR",
  // EMPLOYEE: "EMPLOYEE",
  // ADVERTIZER: "ADVERTIZER",
  // CONTRACTOR: "CONTRACTOR",
  // FREELANCER: "FREELANCER",
  // INVESTOR: "INVESTOR",
}

modules.export = ROLE